php_packages_extra:
  - php{{ php_version }}
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-opcache
  - php{{ php_version }}-imagick
  - php{{ php_version }}-common
  - php{{ php_version }}-mysql
  - php{{ php_version }}-curl
  - php{{ php_version }}-tidy
  - php{{ php_version }}-json
  - php{{ php_version }}-cli
  - php{{ php_version }}-fpm
  - php{{ php_version }}-zip
  - php{{ php_version }}-xml
  - php{{ php_version }}-gd
  - php{{ php_version }}-pdo
  - php{{ php_version }}-intl
  - php{{ php_version }}-raphf
  - php{{ php_version }}-propro
  - php{{ php_version }}-http
  - php{{ php_version }}-amqp
  - php{{ php_version }}-ldap
  - php{{ php_version }}-memcached
  - php{{ php_version }}-imagick
  - php{{ php_version }}-xdebug
  - php{{ php_version }}-yaml

php_enable_php_fpm: true
php_webserver_daemon: nginx

php_fpm_pools:
  - pool_name: www
    pool_template: www.conf.j2
    pool_listen: "/run/php/php{{php_version}}-fpm.sock"
    pool_pm: dynamic
    pool_pm_max_children: 5
    pool_pm_start_servers: 2
    pool_pm_min_spare_servers: 1
    pool_pm_max_spare_servers: 3
    pool_pm_max_requests: 500